// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('vProfile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('vProfile', async function() {
    try {
      console.log('Navigating to login page...');
      await driver.get("https://admin.stage.vcc.hebronsoft.com/auth/login")
      await driver.manage().window().setRect({ width: 1440, height: 900 })
      
      console.log('Waiting for login form to be present...');
      await driver.wait(until.elementLocated(By.id("login-email")), 10000);
      
      console.log('Filling login form...');
      await driver.findElement(By.id("login-email")).click()
      await driver.findElement(By.id("login-email")).sendKeys("qwe@qwe.com")
      await driver.findElement(By.id("login-pass")).click()
      await driver.findElement(By.id("login-pass")).sendKeys("qweQWE123")
      
      console.log('Clicking login button...');
      await driver.findElement(By.id("log-btn")).click()
      
      console.log('Waiting for navigation after login...');
      await driver.wait(until.elementLocated(By.css(".px14:nth-child(6)")), 10000);
      
      console.log('Clicking menu item...');
      await driver.findElement(By.css(".px14:nth-child(6)")).click()
      
      console.log('Waiting for table to be present...');
      await driver.wait(until.elementLocated(By.css("th:nth-child(5) > .p-column-filter")), 10000);
      
      console.log('Clicking filter and entering email...');
      await driver.findElement(By.css("th:nth-child(5) > .p-column-filter")).click()
      await driver.findElement(By.xpath("//th[5]/input")).sendKeys("oksana.kushniaryk+9@hebronsoft.com")
      
      console.log('Waiting for table to update after filtering...');
      await driver.sleep(2000); // Give time for the table to update
      
      console.log('Looking for table row...');
      const tableRowSelector = '.body-2:nth-child(2) > .body-1';
      await driver.wait(until.elementLocated(By.css(tableRowSelector)), 10000);
      
      console.log('Clicking table row...');
      await driver.findElement(By.css(tableRowSelector)).click()
      
      console.log('Waiting for table to load after row click...');
      await driver.sleep(2000); // Give time for the table to update
      
      // Try multiple selectors for the table header
      const tableHeaderSelectors = [
        '.p-datatable-thead th:first-child',  // First column header
        '.p-datatable-thead th',              // Any column header
        'th[role="columnheader"]:first-child' // First column header with role
      ];
      
      let tableHeader;
      for (const selector of tableHeaderSelectors) {
        try {
          console.log(`Trying to find table header with selector: ${selector}`);
          tableHeader = await driver.wait(until.elementLocated(By.css(selector)), 5000);
          console.log(`Found table header with selector: ${selector}`);
          break;
        } catch (e) {
          console.log(`Selector ${selector} not found, trying next...`);
        }
      }
      
      if (!tableHeader) {
        throw new Error('Could not find table header with any of the selectors');
      }
      
      console.log('Scrolling to table header...');
      await driver.executeScript("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", tableHeader);
      await driver.sleep(500); // Give time for smooth scroll to complete
      
      console.log('Clicking table header...');
      await tableHeader.click()
      
      // Wait for the table to be fully loaded
      console.log('Waiting for table to be fully loaded...');
      await driver.sleep(2000);
      
      // Get all table headers and their text
      console.log('Getting all table headers...');
      const headers = await driver.findElements(By.css('.p-datatable-thead th'));
      console.log(`Found ${headers.length} headers`);
      
      // Log all header texts for debugging
      for (let i = 0; i < headers.length; i++) {
        const text = await headers[i].getText();
        console.log(`Header ${i + 1}: "${text}"`);
      }
      
      // Verify "Project status" header exists
      const projectStatusFound = headers.some(async (header) => {
        const text = await header.getText();
        return text.includes('Project status');
      });
      
      assert(projectStatusFound, 'Could not find header with text "Project status"');
      console.log('Successfully verified "Project status" header is present');
      
      console.log('Waiting for pending status element...');
      const pendingStatusSelector = '.body-2 .pending-status';
      await driver.wait(until.elementLocated(By.css(pendingStatusSelector)), 10000);
      
      console.log('Clicking pending status element...');
      await driver.findElement(By.css(pendingStatusSelector)).click();
      
      console.log('Waiting for status change dialog to appear...');
      // First wait for the dialog container to be present in DOM
      await driver.wait(until.elementLocated(By.xpath("//mat-dialog-container[@id='change-status']")), 10000);
      
      // Then wait for it to be visible
      const statusDialog = await driver.findElement(By.xpath("//mat-dialog-container[@id='change-status']"));
      await driver.wait(until.elementIsVisible(statusDialog), 10000);
      
      // Add a small delay to ensure the dialog is fully rendered
      await driver.sleep(1000);
      
      // Debug: Check if dialog is actually visible
      const isDialogVisible = await statusDialog.isDisplayed();
      console.log(`Status dialog visible: ${isDialogVisible}`);
      
      if (!isDialogVisible) {
        throw new Error('Status dialog is present but not visible');
      }
      
      console.log('Verifying dialog content...');
      const firstOptionText = await driver.findElement(By.xpath("//label/div[2]")).getText();
      console.log(`First option text found: "${firstOptionText}"`);
      assert.strictEqual(firstOptionText, "Approved", 'Expected "Approved" text not found');
      
      const secondOptionText = await driver.findElement(By.xpath("//div[2]/mat-radio-button/label/div[2]")).getText();
      console.log(`Second option text found: "${secondOptionText}"`);
      assert.strictEqual(secondOptionText, "Denied", 'Expected "Denied" text not found');
      
      console.log('Selecting Denied status...');
      // Using a more reliable XPath that finds the radio button by its label text
      const deniedRadioButton = await driver.findElement(By.xpath("//mat-radio-button[.//div[contains(text(), 'Denied')]]"));
      await deniedRadioButton.click();
      
      console.log('Waiting for reason options to appear...');
      await driver.sleep(1000); // Give time for reason options to load

      // Verify the reason "Why denied?" - "Potential volunteer did not meet the requirements for this opportunity" is Clickable.

      console.log('Selecting reason for denied...');
      const reasonRadioButton = await driver.findElement(By.xpath("//mat-radio-button[.//div[contains(text(), 'Potential volunteer did not meet the requirements for this opportunity')]]"));
      await reasonRadioButton.click();
      
      console.log('Clicking Change Status button...');
      await driver.findElement(By.xpath("//button[contains(.,'Change Status')]")).click();
      
      console.log('Waiting for success message...');
      const successMessageSelector = "//*[contains(text(), 'Updated successfully')]";
      await driver.wait(until.elementLocated(By.xpath(successMessageSelector)), 10000);
      const successMessage = await driver.findElement(By.xpath(successMessageSelector));
      assert(await successMessage.isDisplayed(), 'Success message "Updated successfully" not found');
      
      // Wait for the table to update after status change
      await driver.sleep(2000);
      
      // Verify the status has changed to "Denied"
      console.log('Verifying status has changed to Denied...');
      const deniedStatusSelector = '.body-2 .denied-status';
      await driver.wait(until.elementLocated(By.css(deniedStatusSelector)), 10000);
      const deniedStatus = await driver.findElement(By.css(deniedStatusSelector));
      assert(await deniedStatus.isDisplayed(), 'Status did not change to Denied');
      console.log('Successfully verified status changed to Denied');

      console.log('Verifying status change from Pending to Denied...');
      // Wait for the status element to update
      await driver.sleep(2000); // Give time for the status to update
      
      // Find the status element and verify it shows "Denied"
      const statusElement = await driver.findElement(By.css('.body-2 .denied-status'));
      const statusText = await statusElement.getText();
      assert.strictEqual(statusText, 'Denied', 'Status did not change to Denied');
      
      console.log('Test completed successfully');
    } catch (error) {
      console.error('Test failed:', error);
      // Take a screenshot on failure
      try {
        const screenshot = await driver.takeScreenshot();
        console.log('Screenshot taken on failure');
        // You can save the screenshot to a file if needed
      } catch (screenshotError) {
        console.error('Failed to take screenshot:', screenshotError);
      }
      throw error;
    }
  })
})